import Foundation

enum AppLanguage: String { case ko, en }

enum PetStrings {
    static func text(_ korean: String, language: AppLanguage) -> String {
        language == .ko ? korean : english[korean, default: korean]
    }
    static let english: [String: String] = [
        "1주일": "1 week",
        "이달의 목표": "Monthly goal",
        "오늘 가장 중요한 한 가지": "Your most important focus today",
        "한 달을 이끌어 갈 방향": "A direction for the month ahead",
        "플래너 이름 변경": "Rename planner",
        "기본 이름": "Default name",
        "월간 저장": "Save month",
        "일간 자세히": "Daily details",
        "여기서 적은 일정은 일간 플래너에도 함께 표시돼요.": "These tasks also appear in the daily planner.",
        "날짜를 눌러 바로 기록하세요.": "Click a date to write directly.",
        "+ 버튼으로 월간 할 일을 적어보세요.": "Use + to add a monthly task.",
        "월간 할 일 삭제": "Delete monthly task",
        "월간 할 일 추가": "Add monthly task",
        "이번 달 할 일": "Monthly to-dos",
        "월간 메모": "Monthly notes",
        "이번 달에 이루고 싶은 일": "What you want to achieve this month",
        "이번 달 목표": "Monthly goal",
        "앱이 실행 중일 때 소리와 말풍선으로 알려드려요. 잠자기 중 지난 알람은 깨어나면 한 번 알려드려요.": "Sound and bubbles work while the app is running. Alarms missed during sleep appear once after waking.",
        "알람 시간이에요!": "It’s time!",
        "변경 사항은 자동 저장돼요.": "Changes are saved automatically.",
        "매일": "Daily",
        "알람 시각": "Alarm time",
        "알람 삭제": "Delete alarm",
        "알람 메모": "Alarm note",
        "알람 켜기": "Enable alarm",
        "알람 추가": "Add alarm",
        "알람": "Alarms",
        "날짜를 누르면 일간 플래너가 열려요.": "Click a day to open its daily plan.",
        "시작일": "Start date",
        "계획 기간": "Planning period",
        "월간 플래너": "Monthly planner",
        "일간 플래너": "Daily planner",
        "월간": "Monthly",
        "일간": "Daily",
        "1년": "1 year",
        "200일": "200 days",
        "100일": "100 days",
        "1개월": "1 month",
        "함께 작업하기": "Work together",
        "이 Mac에서 팀 업무를 정리하는 모드입니다. 실시간 공동 편집은 지원하지 않습니다.": "Organize team work on this Mac. Live collaboration is not available.",
        "모드별 일정과 노트는 따로 보관돼요.": "Schedules and work notes are saved separately by mode.",
        "미배정": "Unassigned",
        "담당자": "Owner",
        "낮음": "Low",
        "높음": "High",
        "보통": "Normal",
        "우선순위": "Priority",
        "팀 스프린트 업무": "Team sprint tasks",
        "업무와 후속 조치": "Work and follow-ups",
        "공부와 과제 계획": "Study and assignments",
        "고객 검증과 성장 실험": "Customer validation and growth",
        "요구사항과 실행 계획": "Requirements and delivery",
        "디자인 작업과 피드백": "Design and feedback",
        "개발 작업과 검증": "Development and verification",
        "프로젝트": "Project",
        "업무": "Work",
        "과목": "Subject",
        "실험": "Experiment",
        "기능": "Feature",
        "화면": "Screen",
        "모듈": "Module",
        "스프린트 결과 검토": "Review sprint outcomes",
        "진행 상황 공유": "Share progress",
        "담당 업무 합의": "Agree on ownership",
        "지표 확인과 다음 실험": "Review metrics and next experiment",
        "작은 실험 출시": "Launch a small experiment",
        "고객 인터뷰": "Customer interview",
        "막힌 일과 지원 요청": "Blockers and help needed",
        "팀 결정과 의존 작업": "Team decisions and dependencies",
        "이번 스프린트 목표": "Sprint goal",
        "매출 · 비용 · 다음 고객 행동": "Revenue · costs · next customer action",
        "검증 실험과 성공 지표": "Validation experiment and success metric",
        "고객 문제와 이번 주 가설": "Customer problem and weekly hypothesis",
        "작업 노트": "Work notes",
        "플래너 모드": "Planner mode",
        "스타트업 팀": "Startup team",
        "1인 스타트업": "Solo startup",
        "학생": "Student",
        "플래너": "Planner",
        "오늘 날씨": "Today’s weather",
        "날씨 지역 설정": "Weather location",
        "개발자": "Developer",
        "디자이너": "Designer",
        "기획자": "Planner",
        "수험생": "Student",
        "회사원": "Office worker",
        "직군": "Role",
        "직군별 작업 도구": "Tools for your work",
        "재현 방법과 기대 결과": "Reproduction steps and expected result",
        "원인과 해결 아이디어": "Cause and solution ideas",
        "다음에 이어 할 작업": "Where to pick up next",
        "디자인 목적과 사용자": "Design goal and audience",
        "참고 자료와 링크": "References and links",
        "피드백과 수정 방향": "Feedback and revisions",
        "해결할 문제와 성공 기준": "Problem and success criteria",
        "결정 사항과 근거": "Decisions and rationale",
        "위험 요소와 다음 행동": "Risks and next actions",
        "오늘 공부할 범위": "Today’s study scope",
        "틀린 이유와 핵심 개념": "Mistakes and key concepts",
        "다시 복습할 내용": "Topics to revisit",
        "회의 안건과 메모": "Meeting agenda and notes",
        "결정 사항": "Decisions",
        "후속 업무 · 담당자 · 기한": "Follow-ups · owner · due date",
        "재현 확인": "Reproduce the issue",
        "테스트 통과": "Tests pass",
        "변경 내용 검토": "Review changes",
        "가독성 확인": "Check readability",
        "상태별 화면 확인": "Check UI states",
        "전달 파일 정리": "Prepare handoff files",
        "요구사항 확인": "Confirm requirements",
        "우선순위 결정": "Set priorities",
        "담당자와 일정 확인": "Confirm owners and dates",
        "개념 복습": "Review concepts",
        "문제 풀이": "Practice questions",
        "오답 정리": "Review mistakes",
        "오늘의 우선순위": "Today’s priorities",
        "후속 업무 확인": "Check follow-ups",
        "내일 할 일 정리": "Plan tomorrow",
        "날짜와 직군별로 따로 저장돼요.": "Saved separately for each date and role.",
        "작업 팔레트": "Working palette",
        "과목별 예정 / 완료 분량 (분)": "By subject: planned / completed minutes",
        "미분류": "Uncategorized",
        "일정의 분류에 과목을 적으세요. 완료 분량은 체크한 일정의 예정 시간입니다.": "Use task categories for subjects. Completed minutes are the planned duration of checked tasks.",
        "체크리스트를 일정에 추가": "Add checklist to plan",
        "25분 집중": "Focus 25 min",
        "50분 집중": "Focus 50 min",

        "☕ 커피": "☕ Coffee", "색상": "Color", "일정 색상": "Task color",
        "달토끼 플래너": "Moon Rabbit Planner", "하루 일정": "Daily schedule",
        "10분 칸 · 눌러서 일정 추가": "10-min blocks · click to add", "30분 칸 · 눌러서 일정 추가": "30-min blocks · click to add",
        "도시·동네 (예: 서울 연남동)": "City or neighborhood",
        "예: 서울 연남동 · 부산 우동 · 제주 애월읍": "Try: Yeonnam-dong, Seoul · U-dong, Busan",
        "한글·영문으로 도시나 동네를 검색하세요.": "Search cities or neighborhoods in Korean or English.",
        "지역 이름을 두 글자 이상 입력하세요.": "Enter at least two characters.",
        "지역을 찾지 못했어요. 시·구와 동네 이름을 함께 입력해 주세요.": "No match. Include the city or district with the neighborhood.",
        "주소를 확인하고 지역을 선택하세요.": "Check the address and select a location.",
        "시간 선택 간격": "Time interval", "10분 단위": "10 minutes", "30분 단위": "30 minutes", "시작 시각": "Start time",
        "시간 (10분 단위)": "Start time (10-minute steps)", "예정 분량 (10분 단위)": "Duration (10-minute steps)",
        "문구와 색상 꾸미기": "Customize text & colors", "플래너 제목": "Planner title",
        "디데이 영역 제목": "Milestone section title", "디데이 표시 문구": "Countdown label",
        "예: 마감 → 마감 −7 · 날짜 계산은 유지돼요.": "Example: Deadline → Deadline −7. Days stay automatic.",
        "플래너 배경": "Planner background", "플래너 카드": "Planner cards", "플래너 강조색": "Planner accent",
        "말풍선 배경": "Bubble background", "말풍선 테두리": "Bubble border", "기본 색상": "Default colors",
        "색상은 바로 적용되며 글자색은 밝기에 맞춰 바뀝니다.": "Colors apply instantly. Text adapts to background brightness.",
        "달빛 작업실": "A little room to focus", "이전 날": "Previous day", "다음 날": "Next day", "오늘": "Today",
        "오늘을 이끌어 줄 한 가지": "ONE THING TO GUIDE YOUR DAY", "하루의 할 일": "Your daily intentions",
        "분류": "Category", "예정 분량": "Planned minutes", "아직 비어 있는 하루, 첫 계획을 적어봐요.": "A fresh page. Add your first intention.",
        "기억하고 싶은 메모": "Notes to keep", "하루 메모": "Daily notes", "기다리는 그날": "LOOKING FORWARD TO",
        "말풍선에 디데이 표시": "Show D-day in bubble", "기념일이나 마감 이름": "Milestone or deadline",
        "이날 집중한 시간": "FOCUS TIME ON THIS DAY", "하루의 리듬": "The rhythm of your day", "일정의 시간과 분량을 표시해요.": "Blocks follow task times and durations.",
        "작은 계획들이 모여 나의 하루가 돼요.": "Little intentions make a day your own.", "하루 저장": "Save your day", "곁에서 응원하고 있어요 🌿": "I'm right here, cheering for you 🌿",

        "저장": "Save", "저장됨 ✓": "Saved ✓", "설정을 저장했어요 ✓": "Settings saved ✓", "일정을 저장했어요 ✓": "Planner saved ✓",
        "말풍선에 목표 표시": "Show goal in bubble", "오늘 일정": "Today's plan", "하루 플래너": "Daily planner", "날짜": "Date",
        "시간": "Time", "할 일 · 완료 체크": "Tasks · Check off", "할 일": "Task", "완료": "Done", "일정 삭제": "Remove task",
        "+ 일정 추가": "+ Add task", "+ 일정 추가로 하루를 계획해 보세요.": "Plan your day with + Add task.",
        "이 Mac에 날짜별로 보관돼요.": "Saved by date on this Mac.", "오늘 일정을 적어볼까요? 🗓": "Let's plan your day 🗓",
        "왼쪽 클릭: 빠른 메뉴 · 오른쪽 클릭: 설정": "Left click: actions · Right click: settings",
        "날씨": "Weather", "도시 이름 (예: Seoul)": "City name (e.g. Seoul)", "검색": "Search", "새로고침": "Refresh",
        "도시를 검색하고 선택하세요.": "Search for a city and select it.", "도시 이름을 두 글자 이상 입력하세요.": "Enter at least two characters.",
        "검색 중…": "Searching…", "도시를 찾지 못했어요. 영문 이름도 시도해 보세요.": "No city found. Try its English name.",
        "도시를 선택하세요.": "Select your city.", "날씨 확인 중…": "Checking the weather…",
        "연결하지 못했어요. 인터넷을 확인하고 다시 시도해 주세요.": "Couldn't connect. Check your connection and try again.",
        "날씨를 열거나 검색·새로고침할 때 인터넷을 사용해요.": "Opening weather, searching and refreshing use the internet.",
        "체감": "Feels like", "바람": "Wind", "현지 시각": "Local time",
        "맑음": "Clear", "대체로 맑음": "Mostly clear", "흐림": "Overcast", "안개": "Fog", "이슬비": "Drizzle", "비": "Rain", "눈": "Snow", "뇌우": "Thunderstorms", "날씨 정보": "Weather conditions",

        "☾ 달토끼": "☾ Moon Rabbit", "달토끼 설정": "Moon Rabbit",
        "집중 중": "Focusing", "쉬는 중": "Paused", "함께 집중 중": "Focusing together",
        "오늘의 목표를 적어주세요": "What would you like to work on?", "오늘의 목표": "Your goal",
        "타이머 방식": "Timer mode", "작업 시간": "Stopwatch", "카운트다운": "Countdown",
        "일시정지": "Pause", "시작": "Start", "설정": "Set", "분": "min", "25분": "25 min", "50분": "50 min",
        "타이머 시간 분": "Timer duration in minutes", "누적": "Total", "초기화": "Reset",
        "🥕 간식": "🥕 Snack", "♡ 웃기": "♡ Smile", "♫ 춤": "♫ Dance", "↟ 스트레칭": "↟ Stretch", "❀ 꽃 주기": "❀ Flower",
        "이동": "Movement", "산책하기": "Wander", "한자리에 있기": "Stay here", "크기": "Size", "토끼 크기": "Rabbit size",
        "클릭: 설정 · 드래그: 이동 · 잠금 시 일시정지": "Click: settings · Drag: move · Locks pause timer",
        "펫 숨기기": "Hide pet", "펫 보이기": "Show pet", "종료": "Quit", "언어": "Language",
        "작업 시간을 0으로 돌릴까요?": "Reset your total work time?", "타이머를 다시 맞출까요?": "Reset the countdown?",
        "누적 작업 시간과 목표는 유지합니다.": "Your total work time and goal will be kept.",
        "지금까지 누적한 시간이 초기화됩니다. 목표는 유지합니다.": "Your total work time will be cleared. Your goal will be kept.",
        "취소": "Cancel", "새로운 시작! 준비됐어요 🌱": "A fresh start! Ready when you are 🌱",
        "안녕! 오늘도 곁에 있을게요 🌸": "Hi! I'll keep you company today 🌸",
        "좋아요! 내가 옆에 있을게요 🌸": "Let's do this! I'm right here with you 🌸",
        "잘했어요. 잠깐 차 한 잔 어때요? 🍵": "Nice work. How about a little tea break? 🍵",
        "잠시 쉬었어요. 메뉴에서 다시 시작해요.": "Time to rest. Resume from my settings.",
        "띵! 정한 시간이 다 됐어요 🎉\n수고했어요. 잠깐 쉬어가요!": "Ding! Your focus time is complete 🎉\nLovely work. Take a little break!"
    ]
}
